In [1]:
favoritelang = ("Python","Julia","R")

("Python", "Julia", "R")

In [2]:
x1 = (1, 2, 3)

(1, 2, 3)

In [3]:
x2 = (1, 2.0, "tmp")

(1, 2.0, "tmp")

In [4]:
x3 = (a=2, b=1+2)

(a = 2, b = 3)

In [5]:
length(x2)

3

In [6]:
x2[1], x2[2], x2[3]

(1, 2.0, "tmp")

In [7]:
с = x1[2] + x1[3]

5

In [8]:
x3.a, x3.b, x3[2]

(2, 3, 3)

In [9]:
in("tmp", x2), 0 in x2

(true, false)

In [10]:
phonebook = Dict("Иванов И.И." => ("867-5309","333-5544"), "Бухгалтерия" => "555-2368")

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [11]:
keys(phonebook)

KeySet for a Dict{String, Any} with 2 entries. Keys:
  "Бухгалтерия"
  "Иванов И.И."

In [12]:
values(phonebook)

ValueIterator for a Dict{String, Any} with 2 entries. Values:
  "555-2368"
  ("867-5309", "333-5544")

In [13]:
pairs(phonebook)

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [14]:
haskey(phonebook, "Иванов И.И.")

true

In [15]:
phonebook["Сидоров П.С."] = "555-3344"

"555-3344"

In [17]:
pop!(phonebook, "Иванов И.И.")

("867-5309", "333-5544")

In [18]:
a = Dict("foo" => 0.0, "bar" => 42.0);
b = Dict("baz" => 17, "bar" => 13.0);
merge(a, b), merge(b,a)

(Dict{String, Real}("bar" => 13.0, "baz" => 17, "foo" => 0.0), Dict{String, Real}("bar" => 42.0, "baz" => 17, "foo" => 0.0))

In [19]:
A = Set([1, 3, 4, 5])

Set{Int64} with 4 elements:
  5
  4
  3
  1

In [20]:
B = Set("abrakadabra")

Set{Char} with 5 elements:
  'a'
  'd'
  'r'
  'k'
  'b'

In [23]:
S1 = Set([1,2]);
S2 = Set([3,4]);
issetequal(S1,S2)

false

In [24]:
S3 = Set([1,2,2,3,1,2,3,2,1]);
S4 = Set([2,3,1]);
issetequal(S3,S4)

true

In [25]:
C=union(S1,S2)

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [26]:
D = intersect(S1,S3)

Set{Int64} with 2 elements:
  2
  1

In [27]:
E = setdiff(S3,S1)

Set{Int64} with 1 element:
  3

In [28]:
issubset(S1,S4)

true

In [30]:
push!(S4, 99)

Set{Int64} with 4 elements:
  2
  99
  3
  1

In [31]:
pop!(S4)

2

In [32]:
empty_array_1 = []

Any[]

In [34]:
empty_array_2 = (Int64)[]

Int64[]

In [35]:
empty_array_3 = (Float64)[]

Float64[]

In [36]:
a = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [38]:
b = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [39]:
A = [[1, 2, 3] [4, 5, 6] [7, 8, 9]]

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [40]:
B = [[1 2 3]; [4 5 6]; [7 8 9]]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [41]:
c = rand(1,8)

1×8 Matrix{Float64}:
 0.0500458  0.574701  0.518604  0.627241  …  0.0781264  0.683654  0.842554

In [43]:
C = rand(2,3)

2×3 Matrix{Float64}:
 0.604089  0.143756   0.423946
 0.339329  0.0441866  0.884767

In [44]:
D = rand(4, 3, 2)

4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.165051  0.275015  0.674567
 0.405609  0.124098  0.695134
 0.518128  0.761084  0.342936
 0.177952  0.168147  0.61943

[:, :, 2] =
 0.838742   0.46502    0.318713
 0.163425   0.839532   0.480772
 0.80575    0.375722   0.935615
 0.0732973  0.0185727  0.974309

In [45]:
roots = [sqrt(i) for i in 1:10]

10-element Vector{Float64}:
 1.0
 1.4142135623730951
 1.7320508075688772
 2.0
 2.23606797749979
 2.449489742783178
 2.6457513110645907
 2.8284271247461903
 3.0
 3.1622776601683795

In [46]:
ar_1 = [3*i^2 for i in 1:2:9]

5-element Vector{Int64}:
   3
  27
  75
 147
 243

In [47]:
ar_2=[i^2 for i=1:10 if (i^2%5!=0 && i^2%4!=0)]

4-element Vector{Int64}:
  1
  9
 49
 81

In [48]:
ones(5)

5-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0

In [49]:
ones(2,3)

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [50]:
zeros(4)

4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [51]:
fill(3.5,(3,2))

3×2 Matrix{Float64}:
 3.5  3.5
 3.5  3.5
 3.5  3.5

In [52]:
repeat([1,2],3,3)

6×3 Matrix{Int64}:
 1  1  1
 2  2  2
 1  1  1
 2  2  2
 1  1  1
 2  2  2

In [54]:
a = collect(1:12)
b = reshape(a,(2,6))

2×6 Matrix{Int64}:
 1  3  5  7   9  11
 2  4  6  8  10  12

In [55]:
b'

6×2 adjoint(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [56]:
с = transpose(b)

6×2 transpose(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [57]:
ar = rand(10:20, 10, 5)

10×5 Matrix{Int64}:
 20  15  10  19  14
 20  16  17  18  10
 19  12  15  13  13
 19  19  20  15  19
 18  20  13  17  16
 18  14  12  13  20
 16  15  13  16  15
 18  16  15  15  20
 12  19  14  11  16
 19  15  10  12  17

In [58]:
ar[:, 2]

10-element Vector{Int64}:
 15
 16
 12
 19
 20
 14
 15
 16
 19
 15

In [59]:
ar[:, [2, 5]]

10×2 Matrix{Int64}:
 15  14
 16  10
 12  13
 19  19
 20  16
 14  20
 15  15
 16  20
 19  16
 15  17

In [60]:
ar[:, 2:4]

10×3 Matrix{Int64}:
 15  10  19
 16  17  18
 12  15  13
 19  20  15
 20  13  17
 14  12  13
 15  13  16
 16  15  15
 19  14  11
 15  10  12

In [61]:
ar[[2, 4, 6], [1, 5]]

3×2 Matrix{Int64}:
 20  10
 19  19
 18  20

In [62]:
ar[1, 3:end]

3-element Vector{Int64}:
 10
 19
 14

In [63]:
sort(ar,dims=1)

10×5 Matrix{Int64}:
 12  12  10  11  10
 16  14  10  12  13
 18  15  12  13  14
 18  15  13  13  15
 18  15  13  15  16
 19  16  14  15  16
 19  16  15  16  17
 19  19  15  17  19
 20  19  17  18  20
 20  20  20  19  20

In [64]:
sort(ar,dims=2)

10×5 Matrix{Int64}:
 10  14  15  19  20
 10  16  17  18  20
 12  13  13  15  19
 15  19  19  19  20
 13  16  17  18  20
 12  13  14  18  20
 13  15  15  16  16
 15  15  16  18  20
 11  12  14  16  19
 10  12  15  17  19

In [65]:
ar .> 14

10×5 BitMatrix:
 1  1  0  1  0
 1  1  1  1  0
 1  0  1  0  0
 1  1  1  1  1
 1  1  0  1  1
 1  0  0  0  1
 1  1  0  1  1
 1  1  1  1  1
 0  1  0  0  1
 1  1  0  0  1

In [66]:
findall(ar .> 14)

34-element Vector{CartesianIndex{2}}:
 CartesianIndex(1, 1)
 CartesianIndex(2, 1)
 CartesianIndex(3, 1)
 CartesianIndex(4, 1)
 CartesianIndex(5, 1)
 CartesianIndex(6, 1)
 CartesianIndex(7, 1)
 CartesianIndex(8, 1)
 CartesianIndex(10, 1)
 CartesianIndex(1, 2)
 CartesianIndex(2, 2)
 CartesianIndex(4, 2)
 CartesianIndex(5, 2)
 ⋮
 CartesianIndex(2, 4)
 CartesianIndex(4, 4)
 CartesianIndex(5, 4)
 CartesianIndex(7, 4)
 CartesianIndex(8, 4)
 CartesianIndex(4, 5)
 CartesianIndex(5, 5)
 CartesianIndex(6, 5)
 CartesianIndex(7, 5)
 CartesianIndex(8, 5)
 CartesianIndex(9, 5)
 CartesianIndex(10, 5)

In [67]:
A = Set([0, 3, 4, 9])
B = Set([1, 3, 4, 7])
C = Set([0, 1, 2, 4, 7, 8, 9])

P = union(intersect(A,B), intersect(A,B), intersect(A,C), intersect(B,C))

Set{Int64} with 6 elements:
  0
  4
  7
  9
  3
  1

In [69]:
S1 = Set(["red", 3.2, false, 5])
S2 = Set(['C', 14, 1.4])
S3 = union(S1, S2)

Set{Any} with 7 elements:
  false
  5
  1.4
  3.2
  14
  "red"
  'C'

In [70]:
S1 = Set(["red", 3.2, false, 5])
S2 = Set(['C', 14, 1.4])
issetequal(S1,S2)

false

In [71]:
S1 = Set(["red", 3.2, false, 5])
S2 = Set(['C', 14, 1.4])
intersect(S1,S2)

Set{Any}()

In [72]:
S1 = Set(["red", 3.2, false, 5])
S2 = Set(['C', 14, 1.4])
setdiff(S2,S1)

Set{Any} with 3 elements:
  1.4
  14
  'C'

In [74]:
S1 = Set(["red", 3.2, false, 5])
S2 = Set(['C', 14, 1.4])
issubset(S1,S2)

false

In [76]:
push!(S2, "red")

Set{Any} with 5 elements:
  5
  1.4
  14
  "red"
  'C'

In [77]:
pop!(S2)

5

In [78]:
S2

Set{Any} with 4 elements:
  1.4
  14
  "red"
  'C'

In [79]:
N = 21
arr1_1 = collect(1:N)
arr1_2 = [i for i in 1:N]
arr1_3 = collect(range(1, stop=N, length=N))

println(" Способ 1: ", arr1_1)
println(" Способ 2: ", arr1_2)
println(" Способ 3: ", arr1_3)

 Способ 1: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
 Способ 2: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
 Способ 3: [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0]


In [81]:
arr2_1 = collect(N:-1:1)
arr2_2 = [N-i+1 for i in 1:N]
arr2_3 = reverse(arr1_1)

println(" Способ 1: ", arr2_1)
println(" Способ 2: ", arr2_2)
println(" Способ 3: ", arr2_3)

 Способ 1: [21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
 Способ 2: [21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
 Способ 3: [21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [82]:
arr3_1 = vcat(1:N-1, N:-1:1)
arr3_2 = [i <= N ? i : 2*N-i for i in 1:2*N-1]
arr3_3 = vcat(collect(1:N), collect(N-1:-1:1))

println(" Способ 1: ", arr3_1)
println(" Способ 2: ", arr3_2)
println(" Способ 3: ", arr3_3)

 Способ 1: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
 Способ 2: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
 Способ 3: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [84]:
tmp = [4, 6, 3]

3-element Vector{Int64}:
 4
 6
 3

In [86]:
arr5 = fill(tmp[1], 10)
arr5_alt = repeat([tmp[1]], 10)
println(arr5)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4]


In [87]:
arr6 = repeat(tmp, 10)
arr6_alt = vcat([tmp for _ in 1:10]...)
println(arr6)

[4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3]


In [88]:
arr7 = vcat(fill(tmp[1], 11), fill(tmp[2], 10), fill(tmp[3], 10))

31-element Vector{Int64}:
 4
 4
 4
 4
 4
 4
 4
 4
 4
 4
 4
 6
 6
 ⋮
 6
 6
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3

In [89]:
arr8 = vcat(fill(tmp[1], 10), fill(tmp[2], 20), fill(tmp[3], 30))

60-element Vector{Int64}:
 4
 4
 4
 4
 4
 4
 4
 4
 4
 4
 6
 6
 6
 ⋮
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3

In [97]:
import Base.count
elements = [2^tmp[1], 2^tmp[2], 2^tmp[3], 2^tmp[3], 2^tmp[3], 2^tmp[3]]
println("Массив: ", elements)
count_6 = 0
for elem in elements
    str_elem = string(elem)
    count_6 += Base.count(c -> c == '6', str_elem)
end
println("Количество цифр «6»: ", count_6)

Массив: [16, 64, 8, 8, 8, 8]


Количество цифр «6»: 2


In [106]:
using Statistics
x = 3:0.1:6
y = exp.(x) .* cos.(x)
println("Вектор y: ", y)
mean_y = mean(y)
println("Среднее значение y: ", mean_y)

Вектор y: [-19.884530844146987, -22.178753389342127, -24.490696732801293, -26.77318244299338, -28.969237768093574, -31.011186439374516, -32.819774760338504, -34.30336011037369, -35.35719361853035, -35.86283371230767, -35.68773248011913, -34.68504225166807, -32.693695428321746, -29.538816297262983, -25.032529229039966, -18.975233154958957, -11.157417389647478, -1.3620985182057503, 10.632038010191998, 25.046704998273004, 42.09920106253839, 61.99663027669454, 84.92906736250268, 111.0615860420258, 140.5250750527875, 173.40577640857734, 209.73349424783467, 249.46844055885668, 292.4867067371223, 338.5643778585117, 387.36034029093076]
Среднее значение y: 53.11374594642971


In [107]:
x = 0.1
y = 0.2
i = 3:3:36
j = 1:3:34

x_i = x .^ i
y_j = y .^ j
vector = zip(x_i, y_j)

for (xi, yj) in vector
    println((xi, yj))
end

(0.0010000000000000002, 0.2)
(1.0000000000000004e-6, 0.0016000000000000003)
(1.0000000000000005e-9, 1.2800000000000006e-5)
(1.0000000000000008e-12, 1.0240000000000006e-7)
(1.0000000000000009e-15, 8.192000000000005e-10)
(1.0000000000000008e-18, 6.5536000000000055e-12)
(1.0000000000000012e-21, 5.2428800000000056e-14)
(1.0000000000000012e-24, 4.194304000000005e-16)
(1.0000000000000015e-27, 3.3554432000000044e-18)
(1.0000000000000017e-30, 2.684354560000004e-20)
(1.0000000000000018e-33, 2.147483648000004e-22)
(1.000000000000002e-36, 1.7179869184000035e-24)


In [108]:
M = 25
vector_2i_over_i = [2^i / i for i in 1:M]

25-element Vector{Float64}:
      2.0
      2.0
      2.6666666666666665
      4.0
      6.4
     10.666666666666666
     18.285714285714285
     32.0
     56.888888888888886
    102.4
    186.1818181818182
    341.3333333333333
    630.1538461538462
   1170.2857142857142
   2184.5333333333333
   4096.0
   7710.117647058823
  14563.555555555555
  27594.105263157893
  52428.8
  99864.38095238095
 190650.18181818182
 364722.0869565217
 699050.6666666666
      1.34217728e6

In [109]:
N = 30
vector_fn = ["fn$i" for i in 1:N]

30-element Vector{String}:
 "fn1"
 "fn2"
 "fn3"
 "fn4"
 "fn5"
 "fn6"
 "fn7"
 "fn8"
 "fn9"
 "fn10"
 "fn11"
 "fn12"
 "fn13"
 ⋮
 "fn19"
 "fn20"
 "fn21"
 "fn22"
 "fn23"
 "fn24"
 "fn25"
 "fn26"
 "fn27"
 "fn28"
 "fn29"
 "fn30"

In [111]:
n = 250
x = rand(0:999, n)
y = rand(0:999, n)

vector_y_minus_x = [y[i+1] - x[i] for i in 1:n-1]
vector_x_combination = [x[i] + 2*x[i+1] - x[i+2] for i in 1:n-2]
vector_sin_over_cos = [sin(y[i]) / cos(x[i+1]) for i in 1:n-1]
sum_result = sum(exp.(-x[i+1]) / (x[i] + 10) for i in 1:n-1)
println("Сумма: ", sum_result)

Сумма: 1.3009211220264392e-6


In [117]:
import Pkg; Pkg.add("SpecialFunctions")
using Random
using SpecialFunctions

n = 250
Random.seed!(123)
x = rand(0:999, n)
y = rand(0:999, n)

vector_1 = y[2:end] .- x[1:end-1]
vector_2 = x[1:end-2] .+ 2 .* x[2:end-1] .- x[3:end]
vector_3 = sin.(y[1:end-1]) ./ cos.(x[2:end])
vector_3[abs.(cos.(x[2:end])) .< 1e-10] .= NaN
sum_result = sum(exp.(-x[2:end]) ./ (x[1:end-1] .+ 10))
y_gt_600 = y[y .> 600]
indices_y_gt_600 = findall(y .> 600)
x_corresponding = x[indices_y_gt_600]
x_mean = mean(x)
vector_sqrt_diff = sqrt.(abs.(x .- x_mean))
max_y = maximum(y)
count_within_200 = sum(abs.(y .- max_y) .<= 200)
even_count = sum(iseven.(x))
odd_count = sum(.!(iseven.(x)))
count_multiple_of_7 = sum(x .% 7 .== 0)
x_sorted_by_y = x[sortperm(y)]
top_10_x = sort(x, rev=true)[1:10]
unique_x = unique(x)

println("Вектор 1 (y_i - x_(i-1)), длина: $(length(vector_1))")
println(vector_1)

println("\nВектор 2 (x_i + 2x_(i+1) - x_(i+2)), длина: $(length(vector_2))")
println(vector_2)

println("\nВектор 3 (sin(y_i)/cos(x_(i+1))), длина: $(length(vector_3))")
println(vector_3)

println("\nРезультат суммы: $sum_result")

println("Элементы y > 600: ", y_gt_600)
println("Индексы элементов y > 600: ", indices_y_gt_600)

println("Значения x на тех же позициях: ", x_corresponding)

println("Вектор sqrt(|x – x̄|): ", vector_sqrt_diff)

println("Элементов y, отстоящих от max(y) не более чем на 200: ", count_within_200)

println("Чётных элементов в x: ", even_count)
println("Нечётных элементов в x: ", odd_count)

println("Элементов x, кратных 7: ", count_multiple_of_7)

println("x, отсортированный по возрастанию y: ", x_sorted_by_y)

println("Топ-10 наибольших элементов x: ", top_10_x)

println("Уникальные элементы x: ", unique_x)

   Resolving package versions...
   Installed LogExpFunctions ───── v0.3.29
   Installed OpenSpecFun_jll ───── v0.5.6+0
   Installed IrrationalConstants ─ v0.2.6
   Installed DocStringExtensions ─ v0.9.5
   Installed SpecialFunctions ──── v2.7.1
  Installing 1 artifacts
   Installed artifact OpenSpecFun 263.5 KiB
    Updating `C:\Users\eldar\.julia\environments\v1.12\Project.toml`
  [276daf66] + SpecialFunctions v2.7.1
    Updating `C:\Users\eldar\.julia\environments\v1.12\Manifest.toml`
  [ffbed154] + DocStringExtensions v0.9.5
  [92d709cd] + IrrationalConstants v0.2.6
  [2ab3a3ac] + LogExpFunctions v0.3.29
  [276daf66] + SpecialFunctions v2.7.1
  [efe28fd5] + OpenSpecFun_jll v0.5.6+0
  [37e2e46d] + LinearAlgebra v1.12.0
  [e66e0078] + CompilerSupportLibraries_jll v1.3.0+1
  [4536629a] + OpenBLAS_jll v0.3.29+0
  [05823500] + OpenLibm_jll v0.8.7+0
  [8e850b90] + libblastrampoline_jll v5.13.1+1
Precompiling packages...
   1164.2 ms  ✓ DocStringExtensions
    959.5 ms  ✓ OpenSpecFun_jll


Вектор 1 (y_i - x_(i-1)), длина: 249
[-211, -124, -794, 460, 228, 521, 626, -11, 187, 328, 298, -582, 807, -200, 177, 803, -549, -320, -499, 528, 432, -304, -800, 504, -234, 69, 176, -205, 77, -340, 236, 650, -515, 236, 831, 613, 595, 682, 685, -94, 382, -540, 217, -68, -74, -626, 47, 258, 489, -496, 138, 417, 81, 337, -528, 34, -368, -65, 30, 152, 560, 649, -224, -439, 66, -732, 231, 185, 16, -297, 643, -274, -663, -57, -527, 242, 54, 241, 118, -158, -547, 194, 479, 91, 471, -393, 72, 386, 111, 382, -508, -480, -578, 340, 689, 361, 76, 92, -76, -449, 297, -1, 31, 260, -400, -864, -114, -782, 297, 175, 307, 570, -678, -529, -277, 824, -354, 127, 811, 806, -536, 56, -83, -620, 231, 339, 176, -221, 566, 509, 21, 109, -514, -49, 645, -9, -149, -73, 108, 176, 585, 525, 306, -237, 634, 90, 476, -709, -210, -975, 424, -168, 311, -172, 83, -20, -655, 63, -15, -529, 552, 29, 673, -38, -389, 415, 419, 215, 41, -127, 317, -853, 392, 348, -144, 131, -23, 308, 69, -614, -72, -129, 757, -113, -343,

In [118]:
squares = [i^2 for i in 1:100]

100-element Vector{Int64}:
     1
     4
     9
    16
    25
    36
    49
    64
    81
   100
   121
   144
   169
     ⋮
  7921
  8100
  8281
  8464
  8649
  8836
  9025
  9216
  9409
  9604
  9801
 10000

In [1]:
using Primes

myprimes = primes(1000)[1:168]
eighty_ninth_prime = myprimes[89]
println("89-е наименьшее простое число: $eighty_ninth_prime")

slice_89_to_99 = myprimes[89:99]
println("Срез с 89-го по 99-й элемент: $slice_89_to_99")

89-е наименьшее простое число: 461
Срез с 89-го по 99-й элемент: [461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523]


In [121]:
sum_result = 0

for i in 10:100
    sum_result += i^3 + 4 * i^2
end

println("Результат суммы: ", sum_result)

Результат суммы: 26852735


In [122]:
M = 25
sum_result = 0

for i in 1:M
    term1 = 2^i / i
    term2 = 3^i / (i^2) 
    sum_result += term1 + term2
end

println("Результат суммы: ", sum_result)

Результат суммы: 2.1291704368143802e9


In [123]:
result = 1.0
current_product = 1.0

for numerator in 2:2:38
    denominator = numerator + 1
    current_product *= numerator / denominator
    result += current_product
end

# Выводим результат
println("Результат выражения: ", result)

Результат выражения: 6.976346137897618
