In [1]:
n = 0
while n < 10
n += 1
println(n)
end

1
2
3
4
5
6
7
8
9
10


In [2]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]
i = 1
while i <= length(myfriends)
friend = myfriends[i]
println("Hi $friend, it's great to see you!")
i += 1
end

Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


In [3]:
for n in 1:2:10
println(n)
end

1
3
5
7
9


In [4]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]
for friend in myfriends
println("Hi $friend, it's great to see you!")
end

Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


In [7]:
m, n = 5, 5
A = fill(0, (m, n))
for i in 1:m
for j in 1:n
A[i, j] = i + j
end
end
A

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [9]:
B = fill(0, (m, n))
for i in 1:m, j in 1:n
B[i, j] = i + j
end
B
C = [i + j for i in 1:m, j in 1:n]
C

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [12]:
println("Введите число: ")
N = parse(Int, readline())
if (N % 3 == 0) && (N % 5 == 0)
println("FizzBuzz")
elseif N % 3 == 0
println("Fizz")
elseif N % 5 == 0
println("Buzz")
else
println(N)
end

Введите число: 


stdin>  15


FizzBuzz


In [13]:
x = 5
y = 10
(x > y) ? x : y

10

In [14]:
function sayhi(name)
println("Hi $name, it's great to see you!")
end

sayhi (generic function with 1 method)

In [15]:
function f(x)
x^2
end

f (generic function with 1 method)

In [16]:
sayhi("C-3PO")
f(42)

Hi C-3PO, it's great to see you!


1764

In [17]:
sayhi2(name) = println("Hi $name, it's great to see you!")
f2(x) = x^2

f2 (generic function with 1 method)

In [18]:
sayhi3 = name -> println("Hi $name, it's great to see you!")
f3 = x -> x^2

#8 (generic function with 1 method)

In [21]:
v = [3, 5, 2]
sort(v)
println(v)
sort!(v)
println(v)

[3, 5, 2]
[2, 3, 5]


In [23]:
f(x) = x^2
map(f, [1, 2, 3])

3-element Vector{Int64}:
 1
 4
 9

In [25]:
x -> x^3
map(x -> x^3, [1, 2, 3])

3-element Vector{Int64}:
  1
  8
 27

In [26]:
f(x) = x^2
broadcast(f, [1, 2, 3])
f.([1, 2, 3])

3-element Vector{Int64}:
 1
 4
 9

In [27]:
A = [i + 3*j for j in 0:2, i in 1:3]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [28]:
f(A)

3×3 Matrix{Int64}:
  30   36   42
  66   81   96
 102  126  150

In [29]:
B = f.(A)

3×3 Matrix{Int64}:
  1   4   9
 16  25  36
 49  64  81

In [30]:
A .+ 2 .* f.(A) ./ A
@. A + 2 * f(A) / A

3×3 Matrix{Float64}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

In [31]:
broadcast(x -> x + 2 * f(x) / x, A)

3×3 Matrix{Float64}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

In [32]:
import Pkg
Pkg.add("Example")

    Updating registry at `C:\Users\eldar\.julia\registries\General.toml`
   Resolving package versions...
   Installed Example ─ v0.5.5
    Updating `C:\Users\eldar\.julia\environments\v1.12\Project.toml`
  [7876af07] + Example v0.5.5
    Updating `C:\Users\eldar\.julia\environments\v1.12\Manifest.toml`
  [7876af07] + Example v0.5.5
Precompiling packages...
   1168.0 ms  ✓ Example
  1 dependency successfully precompiled in 3 seconds. 49 already precompiled.


In [33]:
Pkg.add("Colors")
using Colors
palette = distinguishable_colors(100)
rand(palette, 3, 3)

   Resolving package versions...
   Installed Statistics ──────── v1.11.1
   Installed Reexport ────────── v1.2.2
   Installed FixedPointNumbers ─ v0.8.5
   Installed ColorTypes ──────── v0.12.1
   Installed Colors ──────────── v0.13.1
    Updating `C:\Users\eldar\.julia\environments\v1.12\Project.toml`
  [5ae59095] + Colors v0.13.1
    Updating `C:\Users\eldar\.julia\environments\v1.12\Manifest.toml`
  [3da002f7] + ColorTypes v0.12.1
  [5ae59095] + Colors v0.13.1
  [53c48c17] + FixedPointNumbers v0.8.5
  [189a3867] + Reexport v1.2.2
  [10745b16] + Statistics v1.11.1
Precompiling packages...
    517.9 ms  ✓ Reexport
    703.9 ms  ✓ Statistics
   2016.6 ms  ✓ FixedPointNumbers
   1519.1 ms  ✓ ColorTypes
    668.4 ms  ✓ ColorTypes → StyledStringsExt
   4498.7 ms  ✓ Colors
  6 dependencies successfully precompiled in 9 seconds. 50 already precompiled.


In [35]:
for i in 1:100
    println("$i -> $(i^2)")
end

1 -> 1
2 -> 4
3 -> 9
4 -> 16
5 -> 25
6 -> 36
7 -> 49
8 -> 64
9 -> 81
10 -> 100
11 -> 121
12 -> 144
13 -> 169
14 -> 196
15 -> 225
16 -> 256
17 -> 289
18 -> 324
19 -> 361
20 -> 400
21 -> 441
22 -> 484
23 -> 529
24 -> 576
25 -> 625
26 -> 676
27 -> 729
28 -> 784
29 -> 841
30 -> 900
31 -> 961
32 -> 1024
33 -> 1089
34 -> 1156
35 -> 1225
36 -> 1296
37 -> 1369
38 -> 1444
39 -> 1521
40 -> 1600
41 -> 1681
42 -> 1764
43 -> 1849
44 -> 1936
45 -> 2025
46 -> 2116
47 -> 2209
48 -> 2304
49 -> 2401
50 -> 2500
51 -> 2601
52 -> 2704
53 -> 2809
54 -> 2916
55 -> 3025
56 -> 3136
57 -> 3249
58 -> 3364
59 -> 3481
60 -> 3600
61 -> 3721
62 -> 3844
63 -> 3969
64 -> 4096
65 -> 4225
66 -> 4356
67 -> 4489
68 -> 4624
69 -> 4761
70 -> 4900
71 -> 5041
72 -> 5184
73 -> 5329
74 -> 5476
75 -> 5625
76 -> 5776
77 -> 5929
78 -> 6084
79 -> 6241
80 -> 6400
81 -> 6561
82 -> 6724
83 -> 6889
84 -> 7056
85 -> 7225
86 -> 7396
87 -> 7569
88 -> 7744
89 -> 7921
90 -> 8100
91 -> 8281
92 -> 8464
93 -> 8649
94 -> 8836
95 -> 9025
96 -> 9

In [36]:
i = 1
while i <= 100
    println("$i -> $(i^2)")
    i += 1
end

1 -> 1
2 -> 4
3 -> 9
4 -> 16
5 -> 25
6 -> 36
7 -> 49
8 -> 64
9 -> 81
10 -> 100
11 -> 121
12 -> 144
13 -> 169
14 -> 196
15 -> 225
16 -> 256
17 -> 289
18 -> 324
19 -> 361
20 -> 400
21 -> 441
22 -> 484
23 -> 529
24 -> 576
25 -> 625
26 -> 676
27 -> 729
28 -> 784
29 -> 841
30 -> 900
31 -> 961
32 -> 1024
33 -> 1089
34 -> 1156
35 -> 1225
36 -> 1296
37 -> 1369
38 -> 1444
39 -> 1521
40 -> 1600
41 -> 1681
42 -> 1764
43 -> 1849
44 -> 1936
45 -> 2025
46 -> 2116
47 -> 2209
48 -> 2304
49 -> 2401
50 -> 2500
51 -> 2601
52 -> 2704
53 -> 2809
54 -> 2916
55 -> 3025
56 -> 3136
57 -> 3249
58 -> 3364
59 -> 3481
60 -> 3600
61 -> 3721
62 -> 3844
63 -> 3969
64 -> 4096
65 -> 4225
66 -> 4356
67 -> 4489
68 -> 4624
69 -> 4761
70 -> 4900
71 -> 5041
72 -> 5184
73 -> 5329
74 -> 5476
75 -> 5625
76 -> 5776
77 -> 5929
78 -> 6084
79 -> 6241
80 -> 6400
81 -> 6561
82 -> 6724
83 -> 6889
84 -> 7056
85 -> 7225
86 -> 7396
87 -> 7569
88 -> 7744
89 -> 7921
90 -> 8100
91 -> 8281
92 -> 8464
93 -> 8649
94 -> 8836
95 -> 9025
96 -> 9

In [37]:
squares = Dict{Int, Int}()
for i in 1:100
    squares[i] = i^2
end

println("Первые 5 элементов словаря:")
for (k, v) in pairs(squares)
    if k <= 5
        println("$k -> $v")
    end
end

Первые 5 элементов словаря:
5 -> 25
4 -> 16
2 -> 4
1 -> 1
3 -> 9


In [38]:
squares = Dict{Int, Int}()
i = 1
while i <= 100
    squares[i] = i^2
    i += 1
end
println("Последние 5 элементов словаря:")
for (k, v) in pairs(squares)
    if k <= 5
        println("$k -> $v")
    end
end

Последние 5 элементов словаря:
5 -> 25
4 -> 16
2 -> 4
1 -> 1
3 -> 9


In [40]:
squares_arr = Int[]
for i in 1:100
    push!(squares_arr, i^2)
end
println("Первые 5 квадратов: ", squares_arr[1:5])
println("Последние 5 квадратов: ", squares_arr[96:100])

Первые 5 квадратов: [1, 4, 9, 16, 25]
Последние 5 квадратов: [9216, 9409, 9604, 9801, 10000]


In [41]:
squares_arr = Int[]
i = 1
while i <= 100
    push!(squares_arr, i^2)
    i += 1
end
println("Первые 5 квадратов: ", squares_arr[1:5])
println("Последние 5 квадратов: ", squares_arr[96:100])

Первые 5 квадратов: [1, 4, 9, 16, 25]
Последние 5 квадратов: [9216, 9409, 9604, 9801, 10000]


In [46]:
println("Введите число: ")
n = parse(Int, readline())
if(n % 2 == 0)
    println(n)
else
    println("нечётное")
end

println(n%2==0 ? n : "нечётное")

Введите число: 


stdin>  2


2
2


In [47]:
add_one(x) = x+1

add_one (generic function with 1 method)

In [48]:
add_one(4)

5

In [50]:
n, m = 2, 3
linear_data = 1:(n * m)
A = reshape(linear_data, n, m) .+ 0
A

2×3 Matrix{Int64}:
 1  3  5
 2  4  6

In [53]:
A = [1 1 3; 5 2 6; -2 -1 -3]
A_cubed = A^3
println("Матрица A:")
println(A)
println("\nA^3:")
println(A_cubed)

Матрица A:
[1 1 3; 5 2 6; -2 -1 -3]

A^3:
[0 0 0; 0 0 0; 0 0 0]


In [56]:
A = [1 1 3; 5 2 6; -2 -1 -3]
println("Исходная матрица A:")
println(A)
A[:, 3] = A[:, 2] + A[:, 3]
println("\nМатрица A после замены третьего столбца:")
A

Исходная матрица A:
[1 1 3; 5 2 6; -2 -1 -3]

Матрица A после замены третьего столбца:


3×3 Matrix{Int64}:
  1   1   4
  5   2   8
 -2  -1  -4

In [57]:
B = zeros(15, 3)
B[:, 1] .= 10 
B[:, 2] .= -10 
B[:, 3] .= 10 
println("Матрица B:")
println(B)
C = B' * B
println("\nМатрица C = B^T * B:")
println(C)

Матрица B:
[10.0 -10.0 10.0; 10.0 -10.0 10.0; 10.0 -10.0 10.0; 10.0 -10.0 10.0; 10.0 -10.0 10.0; 10.0 -10.0 10.0; 10.0 -10.0 10.0; 10.0 -10.0 10.0; 10.0 -10.0 10.0; 10.0 -10.0 10.0; 10.0 -10.0 10.0; 10.0 -10.0 10.0; 10.0 -10.0 10.0; 10.0 -10.0 10.0; 10.0 -10.0 10.0]

Матрица C = B^T * B:
[1500.0 -1500.0 1500.0; -1500.0 1500.0 -1500.0; 1500.0 -1500.0 1500.0]


In [62]:
Z = zeros(Int, 6, 6)
E = ones(Int, 6, 6)

Z1 = copy(Z)
for i in 1:5
    Z1[i, i+1] = 1
    Z1[i+1, i] = 1
end

Z2 = copy(Z)
for i in 1:6
    for j in 1:6
        if (i + j) % 2 == 1
            Z2[i, j] = 1
        end
    end
end

Z3 = copy(Z)
for i in 1:6
    for j in 1:6
        if abs(i - j) == 2
            Z3[i, j] = 1
        end
    end
end

Z3[1,4] = 1; Z3[1,6] = 1
Z3[2,3] = 1; Z3[2,5] = 1
Z3[3,2] = 1; Z3[3,6] = 1
Z3[4,1] = 1; Z3[4,5] = 1
Z3[5,2] = 1
Z3[6,1] = 1; Z3[6,3] = 1

Z4 = copy(Z)
for i in 1:6
    for j in 1:6
        if (i + j) % 2 == 0
            Z4[i, j] = 1
        end
    end
end

println("\nМатрица Z₁:")
println(Z1)
println("\nМатрица Z₂:")
println(Z2)
println("\nМатрица Z₃:")
println(Z3)
println("\nМатрица Z₄:")
println(Z4)


Матрица Z₁:
[0 1 0 0 0 0; 1 0 1 0 0 0; 0 1 0 1 0 0; 0 0 1 0 1 0; 0 0 0 1 0 1; 0 0 0 0 1 0]

Матрица Z₂:
[0 1 0 1 0 1; 1 0 1 0 1 0; 0 1 0 1 0 1; 1 0 1 0 1 0; 0 1 0 1 0 1; 1 0 1 0 1 0]

Матрица Z₃:
[0 0 1 1 0 1; 0 0 1 1 1 0; 1 1 0 0 1 1; 1 1 0 0 1 1; 0 1 1 0 0 0; 1 0 1 1 0 0]

Матрица Z₄:
[1 0 1 0 1 0; 0 1 0 1 0 1; 1 0 1 0 1 0; 0 1 0 1 0 1; 1 0 1 0 1 0; 0 1 0 1 0 1]


In [16]:
function outer(x, y, operation)
    return operation.(x[:,], y')
end
i = 0:4
j = 0:4
A1 = outer(i, j, (x,y) -> x + y)
x = 0:4
y = [1, 2, 4, 8, 16]
A2 = outer(x, y, (a,b) -> b^a)
i = 0:4
j = 0:4
A3 = outer(i, j, (x,y) -> mod1(x + y, 5) - 1)
n = 10
i = 0:n-1
j = 0:n-1
A4 = outer(i, j, (x,y) -> mod1(x + y, n) .- 1)
i = 0:8
j = 0:8
A5 = outer(i, j, (x,y) -> 8 - abs(x - y))
println("A1:\n", A1)
println("A2:\n", A2)
println("A3:\n", A3)
println("A4:\n", A4)
println("A5:\n", A5)

A1:
[0 1 2 3 4; 1 2 3 4 5; 2 3 4 5 6; 3 4 5 6 7; 4 5 6 7 8]
A2:
[1 1 1 1 1; 1 2 4 8 16; 1 4 16 64 256; 1 8 64 512 4096; 1 16 256 4096 65536]
A3:
[4 0 1 2 3; 0 1 2 3 4; 1 2 3 4 0; 2 3 4 0 1; 3 4 0 1 2]
A4:
[9 0 1 2 3 4 5 6 7 8; 0 1 2 3 4 5 6 7 8 9; 1 2 3 4 5 6 7 8 9 0; 2 3 4 5 6 7 8 9 0 1; 3 4 5 6 7 8 9 0 1 2; 4 5 6 7 8 9 0 1 2 3; 5 6 7 8 9 0 1 2 3 4; 6 7 8 9 0 1 2 3 4 5; 7 8 9 0 1 2 3 4 5 6; 8 9 0 1 2 3 4 5 6 7]
A5:
[8 7 6 5 4 3 2 1 0; 7 8 7 6 5 4 3 2 1; 6 7 8 7 6 5 4 3 2; 5 6 7 8 7 6 5 4 3; 4 5 6 7 8 7 6 5 4; 3 4 5 6 7 8 7 6 5; 2 3 4 5 6 7 8 7 6; 1 2 3 4 5 6 7 8 7; 0 1 2 3 4 5 6 7 8]


In [18]:
using LinearAlgebra

A = [1  2  3  4  5;
     2  1  2  3  4;
     3  2  1  2  3;
     4  3  2  1  2;
     5  4  3  2  1]

b = [7; -1; -3; 5; 17]
lu_result = lu(A)
x = A \ b
x

5-element Vector{Float64}:
 -2.0000000000000036
  3.0000000000000058
  4.999999999999998
  1.9999999999999991
 -3.999999999999999

In [19]:
using Random
Random.seed!(123)
M = rand(1:10, 6, 10)
println("Матрица M:")
println(M)
N = 4
count_greater_than_N = sum(M .> N, dims=2)
println("\nКоличество элементов в каждой строке, больших $N:")
println(vec(count_greater_than_N))

M_value = 7
occurrences = sum(M .== M_value, dims=2)
rows_with_two_occurrences = findall(occurrences .== 2)
println("\nСтроки, где число $M_value встречается ровно 2 раза:")
println(rows_with_two_occurrences)

K = 75
column_pairs = Tuple{Int, Int}[]
for j1 in 1:size(M, 2)
    for j2 in (j1 + 1):size(M, 2)
        if sum(M[:, j1] + M[:, j2]) > K
            push!(column_pairs, (j1, j2))
        end
    end
end

println("\nПары столбцов, сумма элементов которых больше $K:")
println(column_pairs)


Матрица M:
[6 1 1 7 4 3 4 4 2 7; 6 10 5 3 2 1 1 9 6 10; 9 6 4 3 1 6 1 3 9 8; 2 4 2 10 4 4 10 10 3 7; 6 6 8 9 5 2 4 9 9 9; 4 9 6 3 8 3 8 8 4 5]

Количество элементов в каждой строке, больших 4:
[3, 6, 5, 4, 8, 6]

Строки, где число 7 встречается ровно 2 раза:
CartesianIndex{2}[CartesianIndex(1, 1)]

Пары столбцов, сумма элементов которых больше 75:
[(1, 8), (1, 10), (2, 8), (2, 10), (4, 8), (4, 10), (8, 9), (8, 10), (9, 10)]


In [21]:
sum1 = 0.0
sum2 = 0.0
# Первая сумма: sum(i=1 to 20) sum(j=1 to 5) i^4 / (3 + i*j)
for i in 1:20
    for j in 1:5
        sum1 += i^4 / (3 + j)
    end
end
# Вторая сумма: sum(i=1 to 20) sum(j=1 to 5) i^4 / (3 + j)
for i in 1:20
    for j in 1:5
        sum2 += i^4 / (3 + i * j)
    end
end

println("Первая сумма: ", sum1)
println("Вторая сумма: ", sum2)

Первая сумма: 639215.2833333334
Вторая сумма: 89912.02146097136
